#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

if [[ ! -f debian/changelog ]]; then
  echo "missing debian/changelog"
  exit 1
fi

echo "preparing generated sources (vendor + next out)..."
scripts/ppa/prepare-source.sh

echo "ensuring orig tarball exists (required for 3.0 (quilt))..."
# debian/changelog version includes debian revision; orig tarball uses the upstream part
full_version="$(dpkg-parsechangelog -SVersion)"
upstream_version="${full_version%%-*}"
orig_tarball="../screenpipe_${upstream_version}.orig.tar.gz"

echo "creating $orig_tarball from prepared working tree..."
# NOTE: vendor-workspace/, vendor-app/, and screenpipe-app-tauri/out/ are generated by prepare-source.sh.
# They must be part of the .orig tarball (upstream) so dpkg-source doesn't try to put binary blobs into debian.tar.xz.
# We exclude debian/ so it stays in the debian tarball, as expected for 3.0 (quilt).
rm -f "$orig_tarball"
tar \
  --sort=name \
  --mtime='UTC 1970-01-01' \
  --owner=0 --group=0 --numeric-owner \
  --exclude='./.git' \
  --exclude='./debian' \
  --exclude='./target' \
  --exclude='./**/node_modules' \
  --exclude='./**/node_modules/**' \
  --exclude='./screenpipe-app-tauri/node_modules' \
  --exclude='./screenpipe-app-tauri/node_modules/**' \
  -czf "$orig_tarball" \
  --transform="s,^\\.,screenpipe-${upstream_version}," \
  .

echo "building source package..."
if [[ -n "${PPA_GPG_KEYID:-}" && -n "${PPA_GPG_PASSPHRASE:-}" ]]; then
  # non-interactive signing (for ci)
  debuild --no-lintian -S -sa \
    -k"$PPA_GPG_KEYID" \
    -p"gpg --batch --yes --pinentry-mode loopback --passphrase ${PPA_GPG_PASSPHRASE}"
else
  # interactive signing (local)
  debuild --no-lintian -S -sa
fi

echo "ok: source package created in parent dir."
