#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

if [[ ! -f debian/changelog ]]; then
  echo "missing debian/changelog"
  exit 1
fi

stage_root="$(mktemp -d)"
stage_dir="$stage_root/screenpipe"
cleanup() {
  rm -rf "$stage_root"
}
trap cleanup EXIT

echo "staging linux ppa source tree (whitelist only)..."
mkdir -p "$stage_dir"

# Only include files/directories needed to build the Ubuntu PPA packages.
# Everything else (docs, windows blobs, caches, etc) is excluded from the staged tree by default.
rsync -a --delete --prune-empty-dirs \
  --include '/Cargo.toml' \
  --include '/Cargo.lock' \
  --include '/rust-toolchain.toml' \
  --include '/debian/***' \
  --include '/scripts/' \
  --include '/scripts/ppa/' \
  --include '/scripts/ppa/***' \
  --include '/screenpipe-*/***' \
  --include '/screenpipe-app-tauri/***' \
  --exclude '/screenpipe-audio/onnxruntime-win-*.zip' \
  --exclude '/screenpipe-app-tauri/src-tauri/onnxruntime-win-*' \
  --exclude '/screenpipe-app-tauri/.next/***' \
  --exclude '/**/node_modules/***' \
  --exclude '/**/target/***' \
  --exclude '/vendor/***' \
  --exclude '/vendor-workspace/***' \
  --exclude '/vendor-app/***' \
  --exclude '*' \
  ./ \
  "$stage_dir/"

cd "$stage_dir"

echo "preparing generated sources in staged tree (vendor + next out)..."
scripts/ppa/prepare-source.sh

echo "ensuring orig tarball exists (required for 3.0 (quilt))..."
# debian/changelog version includes debian revision; orig tarball uses the upstream part
full_version="$(dpkg-parsechangelog -SVersion)"
upstream_version="${full_version%%-*}"
orig_tarball="$stage_root/screenpipe_${upstream_version}.orig.tar.xz"

echo "preflight: sizing orig tarball inputs (sanity check)..."
# this is approximate (filesystem du), but catches obvious bloat before we spend minutes compressing.
du -h -d 1 . | sort -hr | head -n 30
echo "preflight: key inputs"
du -h \
  vendor \
  screenpipe-app-tauri/out \
  screenpipe-app-tauri/.next \
  2>/dev/null || true

# fail fast unless explicitly overridden
max_bytes="${PPA_MAX_ORIG_BYTES:-0}"
if [[ "$max_bytes" != "0" ]]; then
  bytes="$(du -sb . | awk '{print $1}')"
  if [[ "$bytes" -gt "$max_bytes" ]]; then
    echo "preflight: aborting: source tree size ${bytes} bytes exceeds PPA_MAX_ORIG_BYTES=${max_bytes}"
    exit 1
  fi
fi

echo "creating $orig_tarball from prepared working tree..."
# NOTE: vendor/ and screenpipe-app-tauri/out/ are generated by prepare-source.sh.
# They must be part of the .orig tarball (upstream) so dpkg-source doesn't try to put binary blobs into debian.tar.xz.
# We exclude debian/ so it stays in the debian tarball, as expected for 3.0 (quilt).
# Remove any pre-existing orig tarball with other compression (e.g. .gz),
# otherwise dpkg-source/debuild may pick it up and cause huge uploads.
rm -f "../screenpipe_${upstream_version}.orig.tar."* "$orig_tarball"
tar \
  --sort=name \
  --mtime='UTC 1970-01-01' \
  --owner=0 --group=0 --numeric-owner \
  --exclude='./.git' \
  --exclude='./debian' \
  --exclude='./target' \
  --exclude='./**/node_modules' \
  --exclude='./**/node_modules/**' \
  --exclude='./screenpipe-app-tauri/node_modules' \
  --exclude='./screenpipe-app-tauri/node_modules/**' \
  -c . \
  --transform="s,^\\.,screenpipe-${upstream_version}," \
| xz -T0 -9e > "$orig_tarball"

echo "building source package..."
# dpkg-source will refuse "unrepresentable changes" if any build artifacts are present in-tree.
# make the source build hermetic by removing common build output dirs first.
rm -rf target screenpipe-app-tauri/src-tauri/target screenpipe-app-tauri/target

# allow fast local verification without gpg (ci always signs)
if [[ "${PPA_NO_SIGN:-}" == "1" ]]; then
  debuild --no-lintian -S -sa -us -uc
elif [[ -n "${PPA_GPG_KEYID:-}" && -n "${PPA_GPG_PASSPHRASE:-}" ]]; then
  # non-interactive signing (for ci)
  debuild --no-lintian -S -sa \
    -k"$PPA_GPG_KEYID" \
    -p"gpg --batch --yes --pinentry-mode loopback --passphrase ${PPA_GPG_PASSPHRASE}"
else
  # interactive signing (local)
  debuild --no-lintian -S -sa
fi

echo "copying built artifacts back to repo parent dir..."
for f in "$stage_root"/screenpipe_*; do
  [[ -e "$f" ]] || continue
  mv -f "$f" "$repo_root/../"
done

echo "ok: source package created in parent dir."
